changelog:
  categories:
    - title: "🚀 Features & Enhancements"
      labels:
        - "enhancement"
        - "feature"
    - title: "🐛 Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "📝 Documentation"
      labels:
        - "documentation"
        - "docs"
    - title: "🔧 Maintenance & Dependencies"
      labels:
        - "chore"
        - "dependencies"
    - title: "Other Changes"
      labels:
        - "*"
